name: Call a reusable workflow

on:

  workflow_dispatch:

#jobs:
  #call-workflow:
    #uses: ambikaawari/1_terraform/.github/workflows/terraform.yml@v1
jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/terraform.yml


