name: Call a reusable workflow

on:
 pull_request:
    branches:
      - main
  #workflow_dispatch:

#jobs:
  #call-workflow:
    #uses: ambikaawari/1_terraform/.github/workflows/terraform.yml@v1
jobs:
  job1:
    uses: ambikaawari/1_terraform/.github/workflows/terraform.yml@v1


